### ISSUE TITLE
Incorrect return value in Software-Engineering Pre-work. "Programming as a conversation part 1/The Assignment Expression"

### ISSUE THREAD

**Issue by alanbanks229** [learn-co-curriculum/programming-univbasics-the-assignment-expression#4]
The return value is incorrect on the website...

Lesson displays the following:
**recurring_expression_value = 3 * (10 - 6)
=> 18**

It should be:
**recurring_expression_value = 3 * (10 - 6)
=> 12**

**Comment by maxwellbenton** [comment]
Hi @alanbanks229,

Thank you for catching this. We've updated this lesson so that the math example is consistently `3 * (10 - 4)`, which should resolve this issue. This also aligns with the images in the lesson.

Thank you for contributing!
